q = [
     'Cogs.Admin',
     'Cogs.Misc',
     'Cogs.OwnerOnly',
     'Cogs.Internet',
     # 'Cogs.Tags',
     'Cogs.Random',
     'Cogs.Roles',
     'Cogs.Config',
     'Cogs.Bible',
     'Cogs.Reddit',
     'Cogs.Steam',
     'Cogs.Music',
     # 'Cogs.LEGO',
     'Cogs.Animals',
     'Cogs.Levels',
     'Cogs.GameStats',
     'Cogs.Event_Members',
     'Cogs.Event_Starboard',
     'Cogs.Event_Errors',
     'Cogs.AutoModerator',
]

